-- 1. Create copilot_conversations table
create table if not exists copilot_conversations (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  title text default 'Academic Copilot',

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Create copilot_messages table
create table if not exists copilot_messages (
  id bigint generated by default as identity primary key,

  conversation_id bigint not null
    references copilot_conversations(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  role text not null
    check (
      role in ('user', 'assistant')
    ),

  content text not null,
  actions jsonb,
  sources jsonb,

  created_at timestamptz default now()
);

-- 3. Enable Row Level Security
alter table copilot_conversations enable row level security;
alter table copilot_messages enable row level security;

-- 4. RLS Policies for copilot_conversations
create policy "Users can view their own copilot conversations"
  on copilot_conversations for select
  using (auth.uid() = user_id);

create policy "Users can insert their own copilot conversations"
  on copilot_conversations for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own copilot conversations"
  on copilot_conversations for update
  using (auth.uid() = user_id);

create policy "Users can delete their own copilot conversations"
  on copilot_conversations for delete
  using (auth.uid() = user_id);

-- 5. RLS Policies for copilot_messages
create policy "Users can view their own copilot messages"
  on copilot_messages for select
  using (auth.uid() = user_id);

create policy "Users can insert their own copilot messages"
  on copilot_messages for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own copilot messages"
  on copilot_messages for delete
  using (auth.uid() = user_id);
