create table if not exists study_material_topics (
  id bigint generated by default as identity primary key,

  study_material_id bigint not null
    references study_materials(id)
    on delete cascade,

  syllabus_topic_id bigint not null
    references syllabus_topics(id)
    on delete cascade,

  match_score numeric(5,2) not null,

  created_at timestamptz default now(),

  unique(
    study_material_id,
    syllabus_topic_id
  )
);

alter table study_material_topics enable row level security;

create policy "Users can view matched topics of their study materials"
  on study_material_topics for select
  using (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_topics.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

create policy "Users can insert matched topics for their study materials"
  on study_material_topics for insert
  with check (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_topics.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

create policy "Users can update matched topics for their study materials"
  on study_material_topics for update
  using (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_topics.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

create policy "Users can delete matched topics for their study materials"
  on study_material_topics for delete
  using (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_topics.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );
