create table if not exists study_materials (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  subject_id bigint references academic_subjects(id) on delete set null,
  unit_number integer,
  material_type text not null default 'Other',
  original_file_name text not null,
  storage_path text not null,
  extracted_text text,
  extracted_character_count integer default 0,
  processing_status text not null default 'uploaded' check (processing_status in ('uploaded', 'processing', 'processed', 'failed')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table study_materials enable row level security;

create policy "Users can view their own study materials"
  on study_materials for select
  using (auth.uid() = user_id);

create policy "Users can insert their own study materials"
  on study_materials for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own study materials"
  on study_materials for update
  using (auth.uid() = user_id);

create policy "Users can delete their own study materials"
  on study_materials for delete
  using (auth.uid() = user_id);
