-- ============================================================================
-- CoursePilot Social Learning & Enhanced Profile Database Schema
-- Tables: xp_transactions, user_badges, student_profiles extensions
-- ============================================================================

-- 1. XP Transactions Table (Stores verifiable learning XP rewards)
CREATE TABLE IF NOT EXISTS public.xp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL CHECK (amount > 0 AND amount <= 500),
    reason TEXT NOT NULL,
    reference_type TEXT NOT NULL, -- e.g. 'challenge', 'quiz', 'streak', 'focus_session', 'peer_review'
    reference_id TEXT,
    reference_key TEXT UNIQUE, -- Idempotency token e.g. 'challenge_completion:dsa-1:user-uuid'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_xp_transactions_user ON public.xp_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_xp_transactions_created ON public.xp_transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_xp_transactions_key ON public.xp_transactions(reference_key);

-- Enable RLS on xp_transactions
ALTER TABLE public.xp_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own XP transactions"
    ON public.xp_transactions
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own verified XP transactions"
    ON public.xp_transactions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);


-- 2. User Badges Table (Verifiable achievement badges)
CREATE TABLE IF NOT EXISTS public.user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    badge_key TEXT NOT NULL,
    badge_name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    earned_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_badge UNIQUE (user_id, badge_key)
);

CREATE INDEX IF NOT EXISTS idx_user_badges_user ON public.user_badges(user_id);

-- Enable RLS on user_badges
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own badges"
    ON public.user_badges
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own earned badges"
    ON public.user_badges
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);


-- 3. Extend student_profiles with Social & Community fields
ALTER TABLE public.student_profiles 
    ADD COLUMN IF NOT EXISTS avatar_url TEXT,
    ADD COLUMN IF NOT EXISTS bio TEXT,
    ADD COLUMN IF NOT EXISTS reputation INTEGER DEFAULT 50 CHECK (reputation >= 0 AND reputation <= 100),
    ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS current_streak INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS longest_streak INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_activity_date DATE;

-- Allow public profile viewing if is_public = true
CREATE POLICY "Public profiles are viewable by all authenticated users"
    ON public.student_profiles
    FOR SELECT
    USING (is_public = TRUE OR auth.uid() = id);
