-- 1. Create study_packs table
create table if not exists study_packs (
  id bigint generated by default as identity primary key,

  study_material_id bigint not null
    references study_materials(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  summary text,
  key_concepts jsonb,
  definitions jsonb,
  high_yield_points jsonb,
  common_confusions jsonb,
  examples jsonb,
  quick_revision jsonb,

  generated_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique(study_material_id)
);

-- 2. Enable Row Level Security
alter table study_packs enable row level security;

-- 3. RLS Policies
create policy "Users can view their own study packs"
  on study_packs for select
  using (auth.uid() = user_id);

create policy "Users can insert their own study packs"
  on study_packs for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own study packs"
  on study_packs for update
  using (auth.uid() = user_id);

create policy "Users can delete their own study packs"
  on study_packs for delete
  using (auth.uid() = user_id);
