-- 1. Create exam_paper_analysis table
create table if not exists exam_paper_analysis (
  id bigint generated by default as identity primary key,

  study_material_id bigint not null
    references study_materials(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  total_questions integer,
  detected_units jsonb,
  topic_frequency jsonb,
  question_patterns jsonb,
  marks_distribution jsonb,
  difficulty_distribution jsonb,
  repeated_topics jsonb,
  revision_priorities jsonb,

  generated_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique(study_material_id)
);

-- 2. Enable Row Level Security
alter table exam_paper_analysis enable row level security;

-- 3. RLS Policies (Owner-Isolated Access)
create policy "Users can view their own exam paper analysis"
  on exam_paper_analysis for select
  using (auth.uid() = user_id);

create policy "Users can insert their own exam paper analysis"
  on exam_paper_analysis for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own exam paper analysis"
  on exam_paper_analysis for update
  using (auth.uid() = user_id);

create policy "Users can delete their own exam paper analysis"
  on exam_paper_analysis for delete
  using (auth.uid() = user_id);
