-- Enable pgvector extension
create extension if not exists vector;

-- 1. Create study_material_chunks table
create table if not exists study_material_chunks (
  id bigint generated by default as identity primary key,

  study_material_id bigint not null
    references study_materials(id)
    on delete cascade,

  chunk_index integer not null,

  content text not null,

  embedding vector(768),

  page_number integer,

  token_count integer,

  created_at timestamptz default now(),

  unique(study_material_id, chunk_index)
);

-- 2. Create HNSW Cosine Similarity Index
create index if not exists study_material_chunks_embedding_idx
  on study_material_chunks
  using hnsw (embedding vector_cosine_ops);

-- 3. Enable Row Level Security
alter table study_material_chunks enable row level security;

-- 4. RLS Policies
create policy "Users can view chunks of their own study materials"
  on study_material_chunks for select
  using (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_chunks.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

create policy "Users can insert chunks for their own study materials"
  on study_material_chunks for insert
  with check (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_chunks.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

create policy "Users can delete chunks of their own study materials"
  on study_material_chunks for delete
  using (
    exists (
      select 1 from study_materials
      where study_materials.id = study_material_chunks.study_material_id
      and study_materials.user_id = auth.uid()
    )
  );

-- 5. Match Chunks RPC Function for Semantic Similarity Search
create or replace function match_study_material_chunks(
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  target_study_material_id bigint
)
returns table (
  id bigint,
  study_material_id bigint,
  chunk_index int,
  content text,
  page_number int,
  similarity float
)
language plpgsql
security definer
as $$
begin
  return query
  select
    smc.id,
    smc.study_material_id,
    smc.chunk_index,
    smc.content,
    smc.page_number,
    (1 - (smc.embedding <=> query_embedding))::float as similarity
  from study_material_chunks smc
  where smc.study_material_id = target_study_material_id
    and smc.embedding is not null
    and (1 - (smc.embedding <=> query_embedding)) >= match_threshold
  order by smc.embedding <=> query_embedding
  limit match_count;
end;
$$;
