-- ============================================================================
-- CoursePilot Social Challenges, Engagement & Leaderboard Schema
-- Tables: feed_item_likes, saved_feed_items, user_challenge_history, public_learning_profiles
-- ============================================================================

-- 1. Feed Item Helpful / Likes Table
CREATE TABLE IF NOT EXISTS public.feed_item_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    feed_item_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_feed_like UNIQUE (user_id, feed_item_id)
);

CREATE INDEX IF NOT EXISTS idx_feed_likes_item ON public.feed_item_likes(feed_item_id);
CREATE INDEX IF NOT EXISTS idx_feed_likes_user ON public.feed_item_likes(user_id);

ALTER TABLE public.feed_item_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view all feed likes"
    ON public.feed_item_likes
    FOR SELECT
    USING (true);

CREATE POLICY "Users can manage their own feed likes"
    ON public.feed_item_likes
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);


-- 2. Saved Feed Items / Bookmarks Table
CREATE TABLE IF NOT EXISTS public.saved_feed_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    feed_item_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_saved_item UNIQUE (user_id, feed_item_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_items_user ON public.saved_feed_items(user_id);

ALTER TABLE public.saved_feed_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own saved items"
    ON public.saved_feed_items
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert/delete their own saved items"
    ON public.saved_feed_items
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);


-- 3. User Challenge History Table (Strict Non-Repetition & Anti-Gaming)
CREATE TABLE IF NOT EXISTS public.user_challenge_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    challenge_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'attempted')),
    score INTEGER DEFAULT 0,
    passed BOOLEAN DEFAULT FALSE,
    selected_option INTEGER,
    attempted_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT unique_user_challenge_attempt UNIQUE (user_id, challenge_id)
);

CREATE INDEX IF NOT EXISTS idx_challenge_history_user ON public.user_challenge_history(user_id);
CREATE INDEX IF NOT EXISTS idx_challenge_history_item ON public.user_challenge_history(challenge_id);

ALTER TABLE public.user_challenge_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own challenge history"
    ON public.user_challenge_history
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can record their own challenge attempts"
    ON public.user_challenge_history
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own challenge attempts"
    ON public.user_challenge_history
    FOR UPDATE
    USING (auth.uid() = user_id);


-- 4. Extend student_profiles with public display name
ALTER TABLE public.student_profiles 
    ADD COLUMN IF NOT EXISTS public_display_name TEXT,
    ADD COLUMN IF NOT EXISTS daily_sets_completed INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bonus_questions_completed INTEGER DEFAULT 0;


-- 5. Safe Public Learning Profiles View (Zero Personal Private Data)
CREATE OR REPLACE VIEW public.public_learning_profiles AS
SELECT 
    p.id AS user_id,
    COALESCE(
        p.public_display_name,
        CASE WHEN p.is_public = TRUE THEN p.full_name ELSE 'Learner_' || SUBSTRING(p.id::text, 1, 6) END
    ) AS display_name,
    CASE WHEN p.is_public = TRUE THEN p.avatar_url ELSE NULL END AS avatar_url,
    COALESCE(p.reputation, 50) AS reputation,
    COALESCE(p.current_streak, 0) AS current_streak,
    COALESCE(p.longest_streak, 0) AS longest_streak,
    COALESCE(SUM(tx.amount), 0)::INTEGER AS total_xp,
    COUNT(DISTINCT ch.id) AS challenges_solved
FROM public.student_profiles p
LEFT JOIN public.xp_transactions tx ON tx.user_id = p.id
LEFT JOIN public.user_challenge_history ch ON ch.user_id = p.id AND ch.passed = TRUE
GROUP BY p.id, p.public_display_name, p.full_name, p.avatar_url, p.is_public, p.reputation, p.current_streak, p.longest_streak;
