-- 1. Create study_flashcards table
create table if not exists study_flashcards (
  id bigint generated by default as identity primary key,

  study_material_id bigint not null
    references study_materials(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  question text not null,
  answer text not null,

  topic_name text,
  difficulty text default 'medium'
    check (difficulty in ('easy', 'medium', 'hard')),

  source_chunk_ids jsonb,
  review_count integer default 0,
  next_review_at timestamptz default now(),
  last_reviewed_at timestamptz,

  created_at timestamptz default now()
);

-- 2. Create flashcard_reviews table
create table if not exists flashcard_reviews (
  id bigint generated by default as identity primary key,

  flashcard_id bigint not null
    references study_flashcards(id)
    on delete cascade,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  rating text not null
    check (rating in ('again', 'hard', 'good', 'easy')),

  reviewed_at timestamptz default now()
);

-- 3. Enable Row Level Security
alter table study_flashcards enable row level security;
alter table flashcard_reviews enable row level security;

-- 4. RLS Policies for study_flashcards
create policy "Users can view their own flashcards"
  on study_flashcards for select
  using (auth.uid() = user_id);

create policy "Users can insert their own flashcards"
  on study_flashcards for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own flashcards"
  on study_flashcards for update
  using (auth.uid() = user_id);

create policy "Users can delete their own flashcards"
  on study_flashcards for delete
  using (auth.uid() = user_id);

-- 5. RLS Policies for flashcard_reviews
create policy "Users can view their own flashcard reviews"
  on flashcard_reviews for select
  using (auth.uid() = user_id);

create policy "Users can insert their own flashcard reviews"
  on flashcard_reviews for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own flashcard reviews"
  on flashcard_reviews for delete
  using (auth.uid() = user_id);
